# Descriptive Statistics: Measures of Central Tendancy and Variability - Assignment 3

### Import required libraries

In [1]:
import numpy as np
import pandas as pd

## NBA dataset

### Loading dataset

In [2]:
df1 = pd.read_csv("nba.csv")

In [3]:
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
df1.shape

(458, 9)

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

### Data cleaning

In [7]:
df1.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [8]:
df1 = df1.dropna(subset = ['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight'])

In [9]:
df1.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [10]:
df1['College'] = df1['College'].fillna('Unknown')

In [11]:
df1['Salary'] = df1['Salary'].fillna(df1['Salary'].mean())

In [12]:
df1.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [13]:
df1.shape

(457, 9)

In [14]:
df1.duplicated().sum()

np.int64(0)

Thus we handled missing values by dropping wherever there was only 1 missing value. We listed all NaN in College as unknown as trying to impute this categorical column with mode can skew ground truth. Salary was imputed with mean values.
No duplicates found.

### NBA statistics

In [15]:
df1.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.570000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.165781e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.100602e+06
50%     13.000000   26.000000  220.000000  2.869440e+06
75%     25.000000   30.000000  240.000000  6.331404e+06
max     99.000000   40.000000  307.000000  2.500000e+07

##### Group by category:

In [16]:
df1_height = df1.groupby('Height')
df1_height.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5.000000e+06
...,...,...,...,...,...,...,...,...,...
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,Unknown,4.389607e+06
302,Boban Marjanovic,San Antonio Spurs,40.0,C,27.0,7-3,290.0,Unknown,1.200000e+06
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,Unknown,1.000000e+06
329,Spencer Hawes,Charlotte Hornets,0.0,PF,28.0,7-1,245.0,Washington,6.110034e+06
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,Unknown,2.900000e+06

In [17]:
df1_height["Weight"].describe()

        count        mean        std    min     25%    50%     75%    max
Height
5-11      3.0  181.666667  11.547005  175.0  175.00  175.0  185.00  195.0
5-9       1.0  185.000000        NaN  185.0  185.00  185.0  185.00  185.0
6-0      10.0  183.500000  13.074572  161.0  175.00  184.0  188.75  205.0
6-1      16.0  180.750000  11.174375  165.0  172.75  177.0  187.00  205.0
6-10     47.0  244.872340  15.613006  210.0  235.00  245.0  251.00  289.0
6-11     40.0  247.250000  19.986855  200.0  234.25  245.0  261.25  307.0
6-2      16.0  185.375000   9.569918  165.0  180.00  185.0  191.25  200.0
6-3      33.0  192.575758   8.329279  172.0  189.00  190.0  200.00  208.0
6-4      29.0  203.931034  10.885544  185.0  195.00  205.0  213.00  220.0
6-5      32.0  203.718750  12.596042  179.0  195.00  205.0  210.00  230.0
6-6      42.0  211.190476  14.204496  175.0  203.50  211.0  220.00  245.0
6-7      45.0  217.422222  14.962816  185.0  208.00  220.0  226.00  260.0
6-8      43.0  228.046512  15.198611  198.0  218.00  228.0  240.00  260.0
6-9      59.0  233.966102  16.074145  186.0  222.50  235.0  249.00  260.0
7-0      27.0  251.407407  15.102876  220.0  240.00  253.0  262.50  280.0
7-1       7.0  252.142857  12.198751  240.0  245.00  245.0  257.50  275.0
7-2       3.0  254.333333  13.650397  245.0  246.50  248.0  259.00  270.0
7-3       4.0  261.500000  20.872630  240.0  252.00  258.0  267.50  290.0

We group data by height and display statistics of weight.

In [18]:
df1_team = df1.groupby('Team')
df1_team.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5.000000e+06
...,...,...,...,...,...,...,...,...,...
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4.775000e+06
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2.658240e+06
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9.463484e+06
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,Unknown,3.777720e+06
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,1.200000e+07

In [19]:
df1_team['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
Team,,,,,,,,
Atlanta Hawks,15.0,4.860197e+06,5.194508e+06,525093.0,1152260.00,2.854940e+06,6.873240e+06,18671659.0
Boston Celtics,15.0,4.225583e+06,3.036396e+06,1148640.0,1994760.00,3.425510e+06,5.898058e+06,12000000.0
Brooklyn Nets,15.0,3.501898e+06,5.317817e+06,134215.0,947276.00,1.335480e+06,2.512675e+06,19689000.0
Charlotte Hornets,15.0,5.222728e+06,4.538601e+06,189455.0,1543138.00,4.204200e+06,6.665702e+06,13500000.0
Chicago Bulls,15.0,5.785559e+06,6.251088e+06,525093.0,1203290.50,2.380440e+06,7.974380e+06,20093064.0
Cleveland Cavaliers,15.0,7.455425e+06,7.484116e+06,111196.0,1211638.00,4.950000e+06,1.162482e+07,22970500.0
Dallas Mavericks,15.0,4.746582e+06,5.030279e+06,525093.0,1185783.00,3.950313e+06,5.289487e+06,16407500.0
Denver Nuggets,15.0,4.330974e+06,4.165468e+06,258489.0,1647099.50,3.000000e+06,4.593842e+06,14000000.0
Detroit Pistons,15.0,4.477884e+06,4.668478e+06,111444.0,1711452.50,2.891760e+06,5.635000e+06,16000000.0
Golden State Warriors,15.0,5.924600e+06,5.664282e+06,289755.0,1201462.00,3.815000e+06,1.154062e+07,15501000.0
Houston Rockets,15.0,5.018868e+06,6.414749e+06,200600.0,973638.00,2.288205e+06,7.339758e+06,22359364.0
Indiana Pacers,15.0,4.450122e+06,4.584514e+06,211744.0,1053513.00,4.000000e+06,5.697112e+06,17120106.0
Los Angeles Clippers,15.0,6.323643e+06,7.600225e+06,111444.0,1024164.00,3.110796e+06,8.367500e+06,21468695.0
Los Angeles Lakers,15.0,4.784695e+06,6.835688e+06,525093.0,896167.50,1.724250e+06,5.161144e+06,25000000.0
Memphis Grizzlies,18.0,5.328979e+06,4.556591e+06,700902.0,1939075.00,4.842684e+06,5.387635e+06,19688000.0
Miami Heat,15.0,6.146736e+06,7.285680e+06,261894.0,947276.00,2.854940e+06,7.847668e+06,22192730.0
Milwaukee Bucks,16.0,4.350220e+06,4.875071e+06,295327.0,1483589.00,2.254167e+06,5.514330e+06,16407500.0
Minnesota Timberwolves,14.0,4.610884e+06,3.977783e+06,947276.0,1590540.00,3.049180e+06,5.744910e+06,12700000.0
New Orleans Pelicans,19.0,4.355304e+06,4.537874e+06,55722.0,981348.50,2.850000e+06,7.785365e+06,15514031.0
New York Knicks,16.0,4.581494e+06,5.952487e+06,30888.0,921721.75,2.225421e+06,4.949493e+06,22875000.0
Oklahoma City Thunder,15.0,6.251020e+06,6.632400e+06,222888.0,1742280.00,3.344000e+06,8.694215e+06,20158622.0
Orlando Magic,14.0,4.297248e+06,3.068412e+06,845059.0,2311302.00,3.956580e+06,5.144390e+06,11250000.0
Philadelphia 76ers,15.0,2.389039e+06,1.953024e+06,525093.0,947276.00,1.074169e+06,4.020240e+06,6500000.0
Phoenix Suns,15.0,4.229676e+06,5.022561e+06,55722.0,964312.00,2.041080e+06,5.500000e+06,13500000.0
Portland Trail Blazers,15.0,3.220121e+06,2.392741e+06,525093.0,1181398.00,2.854940e+06,4.626144e+06,8042895.0
Sacramento Kings,15.0,4.778911e+06,4.701792e+06,525093.0,998384.50,3.156600e+06,6.880303e+06,15851950.0
San Antonio Spurs,15.0,5.629516e+06,6.396804e+06,200600.0,1045078.00,2.814000e+06,8.750000e+06,19689000.0
Toronto Raptors,15.0,4.741174e+06,4.195943e+06,245177.0,1683000.00,2.900000e+06,6.634338e+06,13600000.0
Utah Jazz,15.0,4.204006e+06,4.467878e+06,900000.0,1262160.00,2.433333e+06,4.276360e+06,15409570.0
Washington Wizards,15.0,5.088576e+06,4.869388e+06,200600.0,1510421.00,4.000000e+06,6.847337e+06,15851950.0

We group data by team and display statistics of salary.

In [20]:
# creating category of age
bins = [19, 25, 31, 36, 40]
labels = ['Young', 'Prime', 'Seasoned', 'Veteran']
df1['AgeGroup'] = pd.cut(df1['Age'], bins = bins, labels = labels)
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,AgeGroup
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06,Young
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06,Young
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06,Prime
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06,Young
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5.000000e+06,Prime

In [21]:
df1_age = df1.groupby('AgeGroup')
df1_age.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,AgeGroup
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06,Young
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06,Young
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06,Prime
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06,Young
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5.000000e+06,Prime
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,Unknown,1.200000e+07,Prime
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1.170960e+06,Young
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2.165160e+06,Young
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6.912869e+06,Prime
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3.425510e+06,Prime
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6.300000e+06,Seasoned
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1.635476e+06,Seasoned
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,2.287500e+07,Seasoned
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,Unknown,7.402812e+06,Seasoned
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,Unknown,9.472760e+05,Seasoned
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,4.842684e+06,Veteran
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3.376000e+06,Veteran
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,Unknown,9.477260e+05,Veteran
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,Unknown,2.500000e+07,Veteran
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,Unknown,8.333334e+06,Veteran

In [22]:
df1_age['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
AgeGroup,,,,,,,,
Young,197.0,3.041840e+06,3.552554e+06,30888.0,947276.00,1.662360e+06,3533333.0,16407501.0
Prime,189.0,6.635459e+06,5.825556e+06,55722.0,1500000.00,4.842684e+06,10151612.0,22970500.0
Seasoned,56.0,5.113016e+06,5.283815e+06,200600.0,1323709.25,3.646250e+06,6350000.0,22875000.0
Veteran,13.0,5.351744e+06,6.508388e+06,222888.0,947726.00,4.088019e+06,5250000.0,25000000.0

We group data by age category and display statistics of salary.

## Iris dataset

### Loading dataset

In [24]:
df2 = pd.read_csv('Iris.csv')

In [25]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [26]:
df2.shape

(150, 6)

In [27]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

### Data Cleaning

In [29]:
df2.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [30]:
df2.duplicated().sum()

np.int64(0)

No null or duplicate values found.

### Statistics for Iris Setosa, Iris Versicolor and Iris Virginica

In [31]:
df2['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [38]:
iris_setosa = df2[df2['Species'] == 'Iris-setosa']

In [39]:
iris_versicolor = df2[df2['Species'] == 'Iris-versicolor']

In [40]:
iris_virginica = df2[df2['Species'] == 'Iris-virginica']

In [41]:
iris_setosa.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [42]:
iris_versicolor.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [43]:
iris_virginica.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

## Inferences

Thus we have displayed summary statistics for the two following datasets:
- NBA: Applied some data cleaning techniques to handle missing values. Used groupby() function to group by Height and Team and displayed summary statistics of Weight and Salary respectively. Also categorized age and grouped by it and displayed summary statistics for the same. As observed, higher the age - higher is the salary.
- Iris dataset: No data cleaning techniques were required. We created new datasets for each of the species by filtering to the columns where data was available and displayed summary statistics for each type of species.