# Data Wrangling - Assignment 1

### Importing required libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

### Loading dataset

In [6]:
df = pd.read_csv("melb_data.csv")

In [7]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  str
 1   Address        13580 non-null  str
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  str
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  str
 6   SellerG        13580 non-null  str
 7   Date           13580 non-null  str
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  str
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  str
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), str(8)
memory usage: 2.2 MB

### Data Preprocessing

Checking and handling missing values:

In [10]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

BuildingArea, YearBuilt, Car and CouncilArea have missing values. We handle them by:
- Imputing BuildingArea and YearBuilt with means: too many meaningful samples to drop
- Imputing Car with means
- Imputing CouncilArea with mode: it is a categorical variable, we cannot perform numeric mean or median operations to handle it. Too many meaningful samples to drop.

In [11]:
df['BuildingArea'] = df['BuildingArea'].fillna(df['BuildingArea'].mean())

In [12]:
df['YearBuilt'] = df['YearBuilt'].fillna(df['YearBuilt'].mean())

In [13]:
df['Car'] = df['Car'].fillna(df['Car'].mean())

In [17]:
df['CouncilArea'] = df['CouncilArea'].fillna(df['CouncilArea'].mode()[0])

mode() returns a series of values (like a list) of most frequently occuring values. [0] ensures that we select the highest occuring value from the same.

In [18]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

Checking duplicates:

In [21]:
df.duplicated().sum()

np.int64(0)

There are no duplicate values present in the dataset.

Summary of statistics:
- count: total number of values present
- mean: average value for any variable
- std: standard deviation from mean for any variable
- min: minimum value for any variable
- max: maximum value for any variable
- 25%, 50%, 75%: tells us about distribution of data in quartiles, only applicable to numerical columns

In [22]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.960433,3990.669241,392.002962,28.972246,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,122.000000,1960.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,151.967650,1964.684217,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,151.967650,1975.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [23]:
df.shape

(13580, 21)

Dimensions of dataframe:
- 13580 rows
- 21 features

In [24]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='str')

In [26]:
df.head(1)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964.684217,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0

Variable descriptions:
- Suburb: location/area in Melbourne where house is available
- Address: exact address of house
- Rooms: number of rooms in the house
- Type: type of property (h - house, u - unit/apt, t - townhouse)
- Price: cost of house
- Method: method of sale (S - sold, SP - sold prior, PI - passed in)
- SellerG: name of real estate agent
- Date: date on which house was sold
- Distance: distance of property from central Melbourne
- Postcode: Postal code of house
- Bedroom2: number of bedrooms
- Bathroom: number of bathrooms
- Car: number of car parking spaces
- Landsize: total area covered by property in sqm
- BuildingArea: total area covered by building in sqm
- YearBuilt: Year in which house was built
- CouncilArea: Governing council area of property
- Latitude, Longitude: Location coordinates of house
- Regionname: region in Melbourne where property is located
- PropertyCount: number of properties in that suburb

Types of variables:
- Categorical: Suburb, Address, Type, Method, SellerG, CouncilArea, RegionName, Postcode
- Numerical: Rooms, Price, Distance, Bedroom2, Bathroom, Car, Landsize, BuildingArea, Latitude, Longitude, PropertyCount

### Data Formatting and Normalization

In [28]:
df.dtypes

Suburb               str
Address              str
Rooms              int64
Type                 str
Price            float64
Method               str
SellerG              str
Date                 str
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea          str
Lattitude        float64
Longtitude       float64
Regionname           str
Propertycount    float64
dtype: object

In [30]:
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

In [31]:
df['Postcode'] = df['Postcode'].astype(int)
df['Bedroom2'] = df['Bedroom2'].astype(int)
df['Bathroom'] = df['Bathroom'].astype(int)
df['Car'] = df['Car'].astype(int)
df['YearBuilt'] = df['YearBuilt'].astype(int)
df['Propertycount'] = df['Propertycount'].astype(int)

In [32]:
df.dtypes

Suburb                      str
Address                     str
Rooms                     int64
Type                        str
Price                   float64
Method                      str
SellerG                     str
Date             datetime64[us]
Distance                float64
Postcode                  int64
Bedroom2                  int64
Bathroom                  int64
Car                       int64
Landsize                float64
BuildingArea            float64
YearBuilt                 int64
CouncilArea                 str
Lattitude               float64
Longtitude              float64
Regionname                  str
Propertycount             int64
dtype: object

We applied type conversion to convert relevant variables to its respective data types.

### Convert categorical variables to numerical

There are 3 ways to convert categorical to numerical values:

##### One Hot Encoding
- We use one hot encoding when there are a smaller number of possible values for categorical variables. It converts each value for a variable to its own variable and assigns a value of '1' if true and '0' if false.

In [34]:
type_encoded = pd.get_dummies(df['Type'], prefix = 'Type')
Regionname_encoded = pd.get_dummies(df['Regionname'], prefix = 'Regionname')

##### Dummy Coding
- It is the same as one hot encoding except it drops 1 column - the values of the other columns implicitly signify the value the missing column would have.

In [35]:
Method_encoded = pd.get_dummies(df['Method'], prefix = 'Method', drop_first = True)

In [39]:
df = pd.concat([df, type_encoded, Regionname_encoded, Method_encoded], axis = 1)

In [43]:
df = df.drop(['Type', 'Regionname', 'Method'], axis = 1)

##### LabelEncoder
- This is a preprocessing method from sklearn that converts all values for a categorical variable to its numerical equivalent. This is done to ensure machine learning models can understand the signal from each dataset.

In [46]:
le = LabelEncoder()
for col in ['Suburb', 'Address', 'SellerG', 'CouncilArea', 'Postcode', 'Date']:
    df[col] = le.fit_transform(df[col])

In [47]:
df.head()

,Suburb,Address,Rooms,Price,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,...,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria,Method_S,Method_SA,Method_SP,Method_VB
0,0,12794,2,1480000.0,23,1,2.5,53,2,1,...,True,False,False,False,False,False,True,False,False,False
1,0,5943,2,1035000.0,23,2,2.5,53,2,1,...,True,False,False,False,False,False,True,False,False,False
2,0,9814,3,1465000.0,23,15,2.5,53,3,2,...,True,False,False,False,False,False,False,False,True,False
3,0,9004,3,850000.0,23,15,2.5,53,3,2,...,True,False,False,False,False,False,False,False,False,False
4,0,10589,4,1600000.0,155,3,2.5,53,3,1,...,True,False,False,False,False,False,False,False,False,True

In [49]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [51]:
df.head()

,Suburb,Address,Rooms,Price,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,...,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria,Method_S,Method_SA,Method_SP,Method_VB
0,0,12794,2,1480000.0,23,1,2.5,53,2,1,...,1,0,0,0,0,0,1,0,0,0
1,0,5943,2,1035000.0,23,2,2.5,53,2,1,...,1,0,0,0,0,0,1,0,0,0
2,0,9814,3,1465000.0,23,15,2.5,53,3,2,...,1,0,0,0,0,0,0,0,1,0
3,0,9004,3,850000.0,23,15,2.5,53,3,2,...,1,0,0,0,0,0,0,0,0,0
4,0,10589,4,1600000.0,155,3,2.5,53,3,1,...,1,0,0,0,0,0,0,0,0,1

### Inference:
- The Melbourne housing dataset covers a wide variety of data points regarding homes in Melbourne.
- Initially the dataset had 21 features and 13580 data entries.
- We handled some missing values found by imputing numerical values with means and imputing categorical values with mode.
- No duplicate values were found.
- We understood available variables and listed their types. We found that the datatypes of some variables were misaligned and performed type conversion to convert it to the appropriate numeric and datetime formats.
- We converted all categorical variables to a quantitative data type using one hot encoding, dummy coding and label encoding.